# Generated by Django 5.1.2 on 2024-10-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
